version: "3"
 
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - /home/yann/Desktop/Job/Prometheus/container/conf:/etc/prometheus
      - /home/yann/Desktop/Job/Prometheus/container/data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - "9090:9090"
