version: "3.8"

services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    #volumes:
      #- ./ini/:/etc/
    #command:
      #- "--config=/etc/grafana.ini"
    ports:
      - "3000:3000"
